spring:
  application:
    name: smilecare-chatbot
  ai:
    model:
      chat: google-genai
      embedding: none
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-3.7-flash

server:
  port: 8080
